name: Continuous Integration

on: [push, pull_request]

permissions:
  contents: read

jobs:
  unix-build:
    name: Unix Build
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Package Dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with nose2
      run: |
        nose2
  windows-build:
    name: Windows Build
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Package Dependencies
      run: |
        pip install -r requirements.txt
      shell: cmd
    - name: Test with nose2
      run: |
        nose2
      shell: cmd
